# Generated by Django 2.2.6 on 2019-10-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('MINT', 'Mint'), ('LIGHTLY', 'Light'), ('AVERAGE', 'Average'), ('HEAVILY', 'Heavy')], default='AVERAGE', max_length=10)),
            ],
        ),
    ]
